<?xml version="1.0" encoding="UTF-8"?>
<project basedir="." name="validate-letters" default="validate-all-xml-schema">
    
    <target name="validate-all-xml-schema" description="Validate multiple XMLs against XML Schema">
        <schemavalidate failonerror="false" fullchecking="true">
            <schema file="${basedir}/odd/out/tei_all.xsd" namespace="http://www.tei-c.org/ns/1.0"/>
            <fileset dir="${basedir}/data/editions">
                <include name="*.xml"/>
            </fileset>
        </schemavalidate>
    </target>
    
</project>