name: validate letters

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of uv and set the python version
      uses: astral-sh/setup-uv@v6
    - name: validate against rng and schematron
      run: uv run validate-all --files "data/editions/*.xml" --rng "odd/out/tei_all.rng" --schematron "odd/out/tillich-briefe-schematron.sch" 
    - name: validate against xsd
      run: ant